### ISSUE TITLE
Foutmelding bij klikken op event

### ISSUE THREAD

**Issue by RoseM001** [hipsynl/hipsy-wordpress-events#1]
404 FOUT
Pagina niet gevonden!
De pagina die je zoekt, is mogelijk verplaatst, verwijderd of heeft mogelijk nooit bestaan.

De events worden getoond, maar als ik klik op het event (zowel met de optie "tickets" als met de optie "naar event") krijg ik een foutmelding

**Comment by jochemgruter** [comment]
@RoseM001 heb je het probleem kunnen oplossen? Zo ja, wat was de oplossing?

**Comment by RoseM001** [comment]
@jochemgruter Uiteindelijk ben ik bezig geweest met een andere plugin voor events. Ik heb toen nog even gekeken op de oude pagina en zag ik dat hij nu opeens wel werkte, terwijl ik niets veranderd heb. Ik weet dus niet waar precies de fout zat of hoe het is opgelost, maar nu doet hij het wel goed.
